env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=9us6tnK58rtprBZUJy2NU1fN5CUI7lONI

language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - gradle jacocoTestReport coveralls
